### ISSUE TITLE
Is there a pytorch version of git loss?

### ISSUE THREAD

**Issue by wangjue-wzq** [kjanjua26/Git-Loss-For-Deep-Face-Recognition#3] opened 2019-07-30 02:29 UTC
Is there a pytorch version of git loss?When I use gitloss for scene classification, the gitloss value does not decline, I don't know if it is a problem I implemented or gitloss itself is not suitable for scene classification.

**Comment by kjanjua26** [comment] 2019-07-30 11:43
Are you using gitloss with softmax or are you solely training it?

**Comment by kjanjua26** [comment] 2019-09-12 21:53
Hey,
Are you still facing the same issue? Did you try coupling softmax with Gitloss? If the issue is solved, please close the issue.

**Closed as completed** 2019-09-17 12:28 UTC
